### PR TITLE
Updates for Julia v1.0.

### PR DESCRIPTION
**Pull request by fredrikekre**
Updates the syntax for Julia v1.0.0. We should also consder including names from the standard libraries. Thoughts?

### CODE REVIEW

**Comment by ViktorQvarfordt** [comment]
To get names from the standard libraries we can do what we've already done for base_modules:

```
  # julia> join(string.(filter!(x -> isa(eval(x), Module) && !Base.isdeprecated(Base, x), [names(Base); names(Core)])), "|")
```

https://github.com/JuliaEditorSupport/Julia-sublime/blob/master/Julia.sublime-syntax#L38

**Comment by fredrikekre** [comment]
Right, I was mostly wondering whether we should or not. Those names are not available by default as the used to be when they were exported from Base.

**Comment by ViktorQvarfordt** [comment]
Ah I see that you've updated those already.

It's a good question of what should be specially highlighted. I vote for specially highlighting only globally defined functions and keywords.

**Comment by fredrikekre** [comment]
Cheers, this is good to go then I think.

**Pull request merged**
