### PR TITLE
update syntax

### PR DESCRIPTION
**Pull request by fredrikekre**
tests probably need to be updated too

### CODE REVIEW

**Comment by fredrikekre** [comment]
Fixed tests, all pass except:
https://github.com/fredrikekre/Julia-sublime/blob/4f1814dd061014e5b144ce89a6afbc9f5dd8e6fe/syntax_test_julia.jl#L205-L207
Which I don't really understand how this PR would break...

**Comment by ViktorQvarfordt** [comment]
Thanks for the PR!

It is a bit worrying that that simple test is failing. What is the test error output? I'm guessing it is the `!`, which often needs to be dealt with carefully. Also, are you sure the test error is introduced in this commit?

**Comment by fredrikekre** [comment]
Yes, tests passes on master so it has to do with the changes here...

**Comment by fredrikekre** [comment]
Oh, and failing test and the output:
```
  Base.filter!()
# ^^^^ support.module
#      ^^^^^^^ support.function
```
```
Packages/Julia-sublime/syntax_test_julia.jl:205:8: [support.function] does not match scope [source.julia meta.function-call.julia variable.function.julia]
Packages/Julia-sublime/syntax_test_julia.jl:205:9: [support.function] does not match scope [source.julia meta.function-call.julia variable.function.julia]
Packages/Julia-sublime/syntax_test_julia.jl:205:10: [support.function] does not match scope [source.julia meta.function-call.julia variable.function.julia]
Packages/Julia-sublime/syntax_test_julia.jl:205:11: [support.function] does not match scope [source.julia meta.function-call.julia variable.function.julia]
Packages/Julia-sublime/syntax_test_julia.jl:205:12: [support.function] does not match scope [source.julia meta.function-call.julia variable.function.julia]
Packages/Julia-sublime/syntax_test_julia.jl:205:13: [support.function] does not match scope [source.julia meta.function-call.julia variable.function.julia]
Packages/Julia-sublime/syntax_test_julia.jl:205:14: [support.function] does not match scope [source.julia meta.function-call.julia variable.function.julia]
FAILED: 7 of 2646 assertions in 1 files failed
[Finished]
```

**Comment by fredrikekre** [comment]
Oh, and it does not seem to be the `!` that is causing the problem, the following test fail with the same error:
```
  Base.filter()
# ^^^^ support.module
#      ^^^^^^ support.function
```
I added that test to the PR too.

**Comment by ViktorQvarfordt** [comment]
I see that you added to `constant.language`, nice. However, you [change the scope of `e` to variable.other](https://github.com/JuliaEditorSupport/Julia-sublime/pull/69/commits/4f1814dd061014e5b144ce89a6afbc9f5dd8e6fe#diff-64f03b578684072bc00e7ae29fcd7cbcR53), is `e` no longer a global constant?

Re. the failing test: `filter` is a built-in function, so it really should have the scope `support.function`. It seems like `filter()` is scoped properly, but not `Base.filter()`. This gives further clues to where the error is. But I have not been able to pinpoint it. I'm guessing it has to do with the fact that you redefine `base_module_func`, I see that you [removed a `?`](https://github.com/JuliaEditorSupport/Julia-sublime/pull/69/commits/4f1814dd061014e5b144ce89a6afbc9f5dd8e6fe#diff-ab08e5c4d116882e2903d91dee204081R48), is this intentional?

**Comment by fredrikekre** [comment]
> However, you change the scope of e to variable.other, is `e` no longer a global constant?

No, it was changed to `ℯ` (`\euler<TAB>`) in the julia repl) in https://github.com/JuliaLang/julia/pull/23427

> I see that you removed a ?, is this intentional?

No... I am sure I double checked such things... Well, that was it, now all the tests pass :) Thanks!

**Comment by ViktorQvarfordt** [comment]
Cool, I'll merge this now. Thanks for your work!

**Pull request merged**
