### PR TITLE
unicode autocomplete

### PR DESCRIPTION
**Pull request by randy3k**
Added the unicode feature from [JuliaUnicode](https://github.com/randy3k/UnicodeCompletion).
(JuliaUnicode is also refactored as UnicodeCompletion.)

The code is not well-tested and has not been tested on Sublime Test 2.

BTW, any chance to add me to the `JuliaEditorSupport` team?

### CODE REVIEW

**Comment by ViktorQvarfordt** [comment]
Great! Regarding the quality of the code, I've been using JuliaUnicode for a while and haven't run into any issues. If there are bugs we'll find them by using it. However, before we merge, it would be good to check that this doesn't break in sublime 2 (or at least breaks gracefully). (Is anyone at all using sublime 2 nowadays?)

I've added you as collaborator to this repo. If you want to be part of ther org JuliaEditorSupport I guess that can be fixed if needed as well. If you feel like making changes to the `tmLanguage` file, know that I'm rewriting it into a `sublime-syntax` file, which fixes a lot of issues, and brings new featurs. I'll push this into a dev branch later today. The `tmLanguage` will, however, remain for compatibility with older versions of sublime.

**Comment by randy3k** [comment]
It should be now ST2 compatible.

I guess we should also move to semitic versioning when it gets mature.

**Comment by ViktorQvarfordt** [comment]
Looks good! Feel free to merge this when you're happy with it.

While we're discussing the tab completion. What do you think of the pop-up menu being shown directly on backslash, rather than on backslash + character? This is to allow for even faster completions. I realize that this would only be meaningful if the last inserted completion(s) are shown at the top in the popup on pressing backslash. What do you think? Would it be easy to implement?

And yes, we should definitely move to semver. I have some major changes to the syntax highlighting currently ongoing, I think that should be merged first, see https://github.com/JuliaEditorSupport/Julia-sublime/issues/21.

**Comment by randy3k** [comment]
Showing the list directly on backslash can be archived by specifying
```json
    "auto_complete_triggers": [
        {
            "characters": "\\",
            "selector": "source.julia"
        }
    ],
```
in `Julia.sublime-settings`. However, I don't think there is a conical way to control the order of the completion list. But it does have some advantages. For example, typing `\lpha` will also show `\alpha` vis fuzzy logic. In earlier code, it only shows options matching `\a...`.

**Comment by ViktorQvarfordt** [comment]
Awesome!

**Pull request merged**
