### PR TITLE
update syntax on `1.8`

### PR DESCRIPTION
**Pull request by t-bltg**
I've noticed that some keywords such as the function `only` were not highlighted, so I think an update to the syntax file is necessary.
Symbols generated on `1.8.1`, and new file tested in `ST4`.

### CODE REVIEW

**Comment by t-bltg** [comment]
@randy3k ?

**Comment by t-bltg** [comment]
bump

**Comment by randy3k** [comment]
LGTM.

**Comment by t-bltg** [comment]
Thanks!

**Pull request merged**
