### PR TITLE
update syntax on 1.9/1.10

### PR DESCRIPTION
**Pull request by t-bltg**
Updated syntax files (follow up of https://github.com/JuliaEditorSupport/Julia-sublime/pull/119) on julia 1.10-rc2.

Added operators from these PRs:
- https://github.com/JuliaLang/julia/pull/37973;
- https://github.com/JuliaLang/julia/pull/34722;
- https://github.com/JuliaLang/julia/pull/39403;
- https://github.com/JuliaLang/julia/pull/49623;
- https://github.com/JuliaLang/julia/pull/39403;
- https://github.com/JuliaLang/julia/pull/36729.

cc @randy3k.

### CODE REVIEW

**Comment by t-bltg** [comment]
@randy3k or @ViktorQvarfordt, bump.

I'd be interested in maintaining this repository, would that be of interest to any of you ?

Thank you.

**Comment by ViktorQvarfordt** [comment]
Yes! How do we make this happen?

**Comment by t-bltg** [comment]
@ViktorQvarfordt, thanks !

I guess the first thing would be giving me contributor (write) access to the repository ;)

**Comment by ViktorQvarfordt** [comment]
That sounds great. I realize I'm not admin for the repo, so I we need input from @randy3k

**Comment by randy3k** [comment]
I am also not an admin for the repo. :)

**Comment by t-bltg** [comment]
@fredrikekre, or @ViralBShah maybe ?

**Comment by ViralBShah** [comment]
@ViktorQvarfordt You should have merge permissions here. @t-bltg Invited you too. Anyone else I should add?

**Comment by t-bltg** [comment]
> Please merge this one - or let me know if I should.

I'll do that now.

@randy3k, correct me if I'm wrong, I guess the next step after the merge would be to create a new tag `1.0.10` on the repository to make it available in https://packagecontrol.io ?

**Comment by t-bltg** [comment]
Thanks, I've just created a new release: https://github.com/JuliaEditorSupport/Julia-sublime/releases/tag/v1.0.10.

**Pull request merged**
