### PR TITLE
Added sublime-completions

### PR DESCRIPTION
**Pull request by phelipe**
I Added auto completion to utf8 .

### CODE REVIEW

**Comment by ViktorQvarfordt** [comment]
I like this! It deprecates the need for [JuliaCompletions](https://packagecontrol.io/packages/JuliaCompletions) or [JuliaUnicode](https://packagecontrol.io/packages/JuliaUnicode).

One could argue that this should not be part of the language support package itself. That might be true for most languages, but the situation here is different. Unicode symbols are part of the language, the REPL has the exact same functionality and there is hight demand for this.

However, before this can be merged I have a few remarks and questions:
- There are a lot of important unicode symbols missing, such as `\otimes ⊗`. Should we just merge the file https://github.com/jakeconnor/JuliaCompletions/blob/master/julia-utf.sublime-completions instead?
- Do we really want completions for every function exported in Base? I.e. functions such as `log` and so on. This feels redundant, and also messy to maintain (for example `sub` is being deprecated in 0.5). How did you create this list?
- Also, please keep the indentation nice and tidy (`.sublime-completions` is in JSON format, so 4 spaces indent etc.)

**Comment by ViktorQvarfordt** [comment]
I did something similar in https://github.com/JuliaEditorSupport/Julia-sublime/blob/master/Julia.sublime-completions.

- This uses the exact same completions as the REPL (so things like `\otimes ⊗` are included). 
- I skipped completion for functions because I think this is more annoying than helpful.

**Comment by phelipe** [comment]
Sorry for the delay in answering , I was busy with work . I used the table available in the documentation ( http://docs.julialang.org/en/release-0.4/manual/unicode-input/ ) to create the file and I removed some symbols because my sublime could not render some correctly. I think  the  font can be a problem with some symbols.

**Comment by ViktorQvarfordt** [comment]
No problems, even though your code didn't get merged it was a good initiative. There are several issues with using a `sublime-completions` file (it messes up backslas colon triggers etc), and it is annoying to have all these completions pop up all the time. The  package JuliaUnicode fixed this in a very nice way and this code is currently being merged into this package. See PR https://github.com/JuliaEditorSupport/Julia-sublime/pull/20

**Pull request closed without merging**
